### ISSUE TITLE
Load Balancing issue.

### ISSUE THREAD

**Issue by 0xD3n** [ctnkaan/Postman-Student-Helper#23]
I have seen that if multiple links are sent continues the bot will warn the user but will not delete the messages. I thought this issue is because of load balancing.

**Comment by ctnkaan** [comment]
Thanks for pointing this out. Will try to add load balancing to the VM this week.

**Comment by ctnkaan** [comment]
I'm trying to add a sharding file but it gives me this error. I could not figure it out. Do you have any ideas @clairefro ?

Error:
![image](https://user-images.githubusercontent.com/59853931/153402824-a0fc718b-5664-43e7-8a1c-0cbd4aaa625c.png)

src/shard.ts:
```
import { ShardingManager } from "discord.js";

const manager = new ShardingManager("./server.ts", {
    token: "<TOKEN>" //for some reason dotenv does not work in this file
});

manager.on("shardCreate", (shard) => console.log(`Launched shard ${shard.id}`));

manager.spawn();
```

**Comment by clairefro** [comment]
Try using the 'require' import syntax (see other files in repo for reference)

To use import syntax you need special config
