### ISSUE TITLE
Feature Request: Suggestions of gender neutral terms

### ISSUE THREAD

**Issue by lem0n4id** [ctnkaan/Postman-Student-Helper#9]
### Feature Request-
As this is a discord bot for Postman Student Community, it would be great if the bot could check all people's messages for _inclusive language_.

Phrases like `hey guys` or words like `bro`, `ma'am` are gendered and these can be replaced with `hey folks` and `people` or `folk`

#### Example:
Someone messages `hey guys! i have some ....`. Here the bot can reply with the message 👇 
```md
@user
You used the word "guys"
This might not be inclusive or welcoming language. 
Please update / edit your message with the following suggestions instead:
"guys" may be insensitive, use "person", "friend", "pal", "folk", "individual" instead
See above ^^
```

<details>
  <summary markdown="span"> Live example (click to expand)</summary>

![image](https://user-images.githubusercontent.com/61219881/139237635-4d97b367-2beb-44f3-845a-9ccb15ea8b65.png)
</details>

### Solution
We can implement this using [alexjs](https://alexjs.com/). There's an implementation([src](https://github.com/EddieHubCommunity/EddieBot/tree/main/src/alexjs)) of this in [EddieHubCommunity discord bot](https://github.com/EddieHubCommunity/EddieBot) already, from which we can take reference.

**Comment by ctnkaan** [comment]
Hello thank you so much for your recommendation! 
I'll ask this one to the Postman and get confirmation so I can get back to you!

**Comment by lem0n4id** [comment]
Cool!

**Comment by lem0n4id** [comment]
Hey @ctnkaan. Just a friendly reminder.
Do let me know if you have any updates! 😄

**Comment by ctnkaan** [comment]
I haven't received any messages. I'll pin them again. Will get back to you as soon as I get a response. @lem0n4id

**Comment by clairefro** [comment]
Hi @ctnkaan and @lem0n4id , sorry for the late reply. This would be a great addition to the bot. Let's go for it! 

For starters let's just try it with a handful of phrases you feel would be helpful to remind people to be sensitive to. As long is it is helpful!

**Comment by lem0n4id** [comment]
Great!

> ### Solution
> 
> We can implement this using [alexjs](https://alexjs.com/). There's an implementation([src](https://github.com/EddieHubCommunity/EddieBot/tree/main/src/alexjs)) of this in [EddieHubCommunity discord bot](https://github.com/EddieHubCommunity/EddieBot) already, from which we can take reference.

We can maybe implement alexjs? @ctnkaan 
I'm not really familiar with javascript, so I won't be able to make any code contributions 😅
